arya:
  rc-path: "/api/v2/rc"
  kyc-path: "/api/v2/kyc"
  invoice-path: "/api/v1/invoice"
  liveness-path: "/api/v1/liveness"
  cheque-path: "/api/v1/cheque"
  salaryslip-path: "/api/v1/salaryslip"
  translation-path: "/api/v1/translation"
  form16-path: "/api/v1/form16"
  pan-gst: "/api/v1/pan-gst"
  ckyc: "/api/v2/ckyc"
  bankmandate: "/api/v1/mandate"
  qr-code: "/api/v1/qr"
  labour-licence: "/api/v1/labour-licence"
  image-quality: "/api/v1/image-quality"
  itr-extraction: "/api/v1/itr-extract"
  motor: "/api/v1/motor"
  signature-detection: "api/v2/signature-detection"
  
